In [1]:
import eikon as ek
import configparser as cp

You should save a text file with **filename** `eikon.cfg` having the following contents:

    [eikon]
    app_id = YOUR_APP_ID_HERE
    
This file should be readily availble (e.g. in the current working directory) for the next steps.

In [2]:
cfg = cp.ConfigParser()
cfg.read('eikon.cfg')  # adjust for different file location

['eikon.cfg']

In [3]:
ek.set_app_key(cfg['eikon']['app_id']) #set_app_id function being deprecated

In [ ]:
#data, err = ek.get_data('0#.SZSA1',['TR.PriceClose','TR.InvestorFullName'])

In [ ]:
#data

In [ ]:
#help(ek.get_data)

In [4]:
main_chain = '0#.FTSE'
#main_chain = '0#.SPX'
main_chain = '0#.HSI'
#main_chain = '0#.SETI'
#main_chain = '0#.JTOPI' #FTSE/JSE SA TOP 40 COMPANIES

In [5]:
data, err = ek.get_data(main_chain,['TR.PriceClose','TR.CompanyName'])

d:\project\compilers\miniconda3\envs\globalcompanysale\lib\site-packages\eikon\data_grid.py:244: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  data = pd.np.array([[get_data_value(value) for value in row] for row in data_dict['data']])

In [6]:
data

   Instrument  Price Close                                 Company Name
0     2388.HK        27.60                   BOC Hong Kong Holdings Ltd
1     2318.HK        91.10      Ping An Insurance Group Co of China Ltd
2     0941.HK        67.05                             China Mobile Ltd
3     0175.HK        15.06                Geely Automobile Holdings Ltd
4     0002.HK        82.20                             CLP Holdings Ltd
5     0388.HK       270.40         Hong Kong Exchanges and Clearing Ltd
6     0003.HK        15.18               Hong Kong and China Gas Co Ltd
7     0019.HK        75.05                            Swire Pacific Ltd
8     1113.HK        51.45                        CK Asset Holdings Ltd
9     2018.HK        56.80                AAC Technologies Holdings Inc
10    0011.HK       163.70                           Hang Seng Bank Ltd
11    0001.HK        70.05                    CK Hutchison Holdings Ltd
12    0688.HK        28.15         China Overseas Land & Investment Ltd
13    3328.HK         5.21                Bank of Communications Co Ltd
14    1398.HK         5.56  Industrial and Commercial Bank of China Ltd
15    1109.HK        36.05                     China Resources Land Ltd
16    2319.HK        29.70                   China Mengniu Dairy Co Ltd
17    0017.HK        10.30                 New World Development Co Ltd
18    0151.HK         6.35                 Want Want China Holdings Ltd
19    0288.HK         8.59                                 WH Group Ltd
20    2007.HK        10.88               Country Garden Holdings Co Ltd
21    1093.HK        19.08                CSPC Pharmaceutical Group Ltd
22    0386.HK         4.23              China Petroleum & Chemical Corp
23    0669.HK        69.15                 Techtronic Industries Co Ltd
24    1299.HK        79.80                                AIA Group Ltd
25    0762.HK         6.79                   China Unicom Hong Kong Ltd
26    0700.HK       411.40                         Tencent Holdings Ltd
27    1088.HK        14.14                  China Shenhua Energy Co Ltd
28    2628.HK        19.48                  China Life Insurance Co Ltd
29    1038.HK        54.85               CK Infrastructure Holdings Ltd
30    1928.HK        40.15                              Sands China Ltd
31    1997.HK        41.50     Wharf Real Estate Investment Company Ltd
32    0939.HK         6.55                 China Construction Bank Corp
33    2382.HK       129.60        Sunny Optical Technology Group Co Ltd
34    0857.HK         3.42                            PetroChina Co Ltd
35    0267.HK         9.44                                    CITIC Ltd
36    0016.HK       115.00                  Sun Hung Kai Properties Ltd
37    0101.HK        18.18                     Hang Lung Properties Ltd
38    1177.HK        11.56                   Sino Biopharmaceutical Ltd
39    0066.HK        45.20                                 MTR Corp Ltd
40    2313.HK       107.40    Shenzhou International Group Holdings Ltd
41    0823.HK        78.05            Link Real Estate Investment Trust
42    0006.HK        56.30                    Power Assets Holdings Ltd
43    1044.HK        61.70       Hengan International Group Company Ltd
44    3988.HK         3.22                            Bank of China Ltd
45    0883.HK        12.08                                    CNOOC Ltd
46    0083.HK        11.02                             Sino Land Co Ltd
47    0012.HK        37.00            Henderson Land Development Co Ltd
48    0005.HK        57.00                            HSBC Holdings PLC
49    0027.HK        57.65               Galaxy Entertainment Group Ltd

In [7]:
data.head()

  Instrument  Price Close                             Company Name
0    2388.HK        27.60               BOC Hong Kong Holdings Ltd
1    2318.HK        91.10  Ping An Insurance Group Co of China Ltd
2    0941.HK        67.05                         China Mobile Ltd
3    0175.HK        15.06            Geely Automobile Holdings Ltd
4    0002.HK        82.20                         CLP Holdings Ltd

In [8]:
rics = list(data.Instrument.values)

In [9]:
rics

['2388.HK',
 '2318.HK',
 '0941.HK',
 '0175.HK',
 '0002.HK',
 '0388.HK',
 '0003.HK',
 '0019.HK',
 '1113.HK',
 '2018.HK',
 '0011.HK',
 '0001.HK',
 '0688.HK',
 '3328.HK',
 '1398.HK',
 '1109.HK',
 '2319.HK',
 '0017.HK',
 '0151.HK',
 '0288.HK',
 '2007.HK',
 '1093.HK',
 '0386.HK',
 '0669.HK',
 '1299.HK',
 '0762.HK',
 '0700.HK',
 '1088.HK',
 '2628.HK',
 '1038.HK',
 '1928.HK',
 '1997.HK',
 '0939.HK',
 '2382.HK',
 '0857.HK',
 '0267.HK',
 '0016.HK',
 '0101.HK',
 '1177.HK',
 '0066.HK',
 '2313.HK',
 '0823.HK',
 '0006.HK',
 '1044.HK',
 '3988.HK',
 '0883.HK',
 '0083.HK',
 '0012.HK',
 '0005.HK',
 '0027.HK']

In [10]:
#rics = rics[:100]
#rics

In [11]:
esg_data, err = ek.get_data(rics, ['TR.TRESGScore','TR.TRESGScoreGrade','TR.ESGPeriodLastUpdateDate'])

In [12]:
esg_data

   Instrument  ESG Score ESG Score Grade ESG Period Last Update Date
0     2388.HK  72.526204              B+        2019-12-13T00:00:00Z
1     2318.HK  59.335833               B        2020-02-07T00:00:00Z
2     0941.HK  70.663397              B+        2020-02-14T00:00:00Z
3     0175.HK  60.725215               B        2020-01-10T00:00:00Z
4     0002.HK  85.932666               A        2020-02-14T00:00:00Z
5     0388.HK  69.844868              B+        2020-02-07T00:00:00Z
6     0003.HK  75.000000              B+        2019-12-13T00:00:00Z
7     0019.HK  62.445163               B        2020-02-14T00:00:00Z
8     1113.HK  51.458176              B-        2020-01-17T00:00:00Z
9     2018.HK  74.211440              B+        2020-01-10T00:00:00Z
10    0011.HK  83.266765              A-        2020-02-07T00:00:00Z
11    0001.HK  73.209950              B+        2020-02-07T00:00:00Z
12    0688.HK  73.734935              B+        2020-02-14T00:00:00Z
13    3328.HK  65.410710               B        2020-02-07T00:00:00Z
14    1398.HK  75.796285              A-        2020-01-10T00:00:00Z
15    1109.HK  29.207107              C-        2019-12-20T00:00:00Z
16    2319.HK  58.930660               B        2020-02-14T00:00:00Z
17    0017.HK  71.563043              B+        2020-02-07T00:00:00Z
18    0151.HK  40.196067               C        2019-12-13T00:00:00Z
19    0288.HK  64.813657               B        2019-12-14T00:00:00Z
20    2007.HK  57.644068              B-        2020-02-07T00:00:00Z
21    1093.HK  38.700723               C        2019-12-20T00:00:00Z
22    0386.HK  68.093834              B+        2020-02-14T00:00:00Z
23    0669.HK  69.000020              B+        2019-12-13T00:00:00Z
24    1299.HK  73.080102              B+        2019-12-19T00:00:00Z
25    0762.HK  61.051413               B        2020-02-14T00:00:00Z
26    0700.HK  68.845747              B+        2020-01-03T00:00:00Z
27    1088.HK  70.692739              B+        2019-12-13T00:00:00Z
28    2628.HK  71.207466              B+        2019-12-20T00:00:00Z
29    1038.HK  48.966291              C+        2020-01-03T00:00:00Z
30    1928.HK  72.262152              B+        2019-12-13T00:00:00Z
31    1997.HK  65.249015               B        2020-01-03T00:00:00Z
32    0939.HK  75.474792              A-        2019-12-13T00:00:00Z
33    2382.HK  53.742256              B-        2019-12-13T00:00:00Z
34    0857.HK  65.981439               B        2020-01-24T00:00:00Z
35    0267.HK  54.099012              B-        2020-01-31T00:00:00Z
36    0016.HK  64.798551               B        2020-02-07T00:00:00Z
37    0101.HK  67.873299              B+        2019-12-13T00:00:00Z
38    1177.HK  51.135796              B-        2020-02-14T00:00:00Z
39    0066.HK  71.370988              B+        2019-12-20T00:00:00Z
40    2313.HK  42.542622              C+        2019-12-13T00:00:00Z
41    0823.HK  74.288250              B+        2020-02-07T00:00:00Z
42    0006.HK  43.577408              C+        2020-02-14T00:00:00Z
43    1044.HK  52.640540              B-        2019-12-27T00:00:00Z
44    3988.HK  70.548693              B+        2020-02-14T00:00:00Z
45    0883.HK  58.763003               B        2020-02-14T00:00:00Z
46    0083.HK  62.387215               B        2019-12-17T00:00:00Z
47    0012.HK  55.795091              B-        2019-12-13T00:00:00Z
48    0005.HK  82.642363              A-        2020-01-31T00:00:00Z
49    0027.HK  56.186243              B-        2020-01-10T00:00:00Z

In [13]:
company_data, err = ek.get_data(rics,['TR.HeadquartersCity',
                                      'TR.RegistrarCity',
                                      'TR.CorCompanyCountry',
                                      'TR.HQMinorRegion',
                                      'TR.HeadquartersRegion'])

In [14]:
company_data

,Instrument,City of Headquarters,Registrar City,Company Location Country,Minor Region of Headquarters,Region of Headquarters
0,2388.HK,None,,Hong Kong,Eastern Asia,Asia
1,2318.HK,SHENZHEN,,China,Eastern Asia,Asia
2,0941.HK,Beijing,,China,Eastern Asia,Asia
3,0175.HK,None,,Hong Kong,Eastern Asia,Asia
4,0002.HK,None,,Hong Kong,Eastern Asia,Asia
5,0388.HK,None,,Hong Kong,Eastern Asia,Asia
6,0003.HK,None,,Hong Kong,Eastern Asia,Asia
7,0019.HK,None,,Hong Kong,Eastern Asia,Asia
8,1113.HK,None,,Hong Kong,Eastern Asia,Asia
9,2018.HK,SHENZHEN,,China,Eastern Asia,Asia
10,0011.HK,None,,Hong Kong,Eastern Asia,Asia
11,0001.HK,None,,Hong Kong,Eastern Asia,Asia
12,0688.HK,None,,Hong Kong,Eastern Asia,Asia
13,3328.HK,SHANGHAI,,China,Eastern Asia,Asia
14,1398.HK,Beijing,,China,Eastern Asia,Asia
15,1109.HK,None,,Hong Kong,Eastern Asia,Asia
16,2319.HK,None,,Hong Kong,Eastern Asia,Asia
17,0017.HK,None,,Hong Kong,Eastern Asia,Asia
18,0151.HK,SHANGHAI,,China,Eastern Asia,Asia
19,0288.HK,None,,Hong Kong,Eastern Asia,Asia
20,2007.HK,FOSHAN,,China,Eastern Asia,Asia
21,1093.HK,Shijiazhuang,,China,Eastern Asia,Asia
22,0386.HK,BEIJING,,China,Eastern Asia,Asia
23,0669.HK,None,,Hong Kong,Eastern Asia,Asia
24,1299.HK,None,,Hong Kong,Eastern Asia,Asia
25,0762.HK,None,,Hong Kong,Eastern Asia,Asia
26,0700.HK,Shenzhen,,China,Eastern Asia,Asia
27,1088.HK,BEIJING,,China,Eastern Asia,Asia
28,2628.HK,BEIJING,,China,Eastern Asia,Asia
29,1038.HK,None,,Hong Kong,Eastern Asia,Asia
30,1928.HK,None,,Macau,Eastern Asia,Asia
31,1997.HK,None,,Hong Kong,Eastern Asia,Asia
32,0939.HK,BEIJING,,China,Eastern Asia,Asia
33,2382.HK,NINGBO,,China,Eastern Asia,Asia
34,0857.HK,BEIJING,,China,Eastern Asia,Asia
35,0267.HK,None,,Hong Kong,Eastern Asia,Asia
36,0016.HK,None,,Hong Kong,Eastern Asia,Asia
37,0101.HK,None,,Hong Kong,Eastern Asia,Asia
38,1177.HK,None,,Hong Kong,Eastern Asia,Asia
39,0066.HK,None,,Hong Kong,Eastern Asia,Asia
40,2313.HK,NINGBO,,China,Eastern Asia,Asia
41,0823.HK,None,,Hong Kong,Eastern Asia,Asia
42,0006.HK,None,,Hong Kong,Eastern Asia,Asia
43,1044.HK,QUANZHOU,,China,Eastern Asia,Asia
44,3988.HK,BEIJING,,China,Eastern Asia,Asia
45,0883.HK,Beijing,,China,Eastern Asia,Asia
46,0083.HK,None,,Hong Kong,Eastern Asia,Asia
47,0012.HK,None,,Hong Kong,Eastern Asia,Asia
48,0005.HK,LONDON,Bristol,United Kingdom,Northern Europe,Europe
49,0027.HK,None,,Hong Kong,Eastern Asia,Asia

In [15]:
#sale_data, err = ek.get_data(rics, ['TR.PriceClose','TR.Price52WeekHigh','TR.Price52WeekLow','TR.BIDPRICE','TR.ASKPRICE'])

In [16]:
#sale_data

In [17]:
test_rics = rics[:5]

In [18]:
segments = ek.get_data(test_rics, ['TR.BGS.GeoTotalRevenue.segmentName'])

In [19]:
revenues = ek.get_data(test_rics, ['TR.BGS.GeoTotalRevenue'], debug=True,raw_output=True)

In [20]:
#ek.get_data('AH.BK', ['TR.BGS.GeoTotalRevenue.segmentName', 'TR.BGS.GeoTotalRevenue','TR.BGS.BusTotalRevenue'])

In [21]:
segments

(   Instrument               Segment Name
 0     2388.HK
 1     2318.HK
 2     0941.HK
 3     0175.HK                        PRC
 4     0175.HK             Eastern Europe
 5     0175.HK                     Africa
 6     0175.HK                Middle East
 7     0175.HK  Central and South America
 8     0175.HK            Other countries
 9     0175.HK              Segment Total
 10    0175.HK         Consolidated Total
 11    0002.HK                  Hong Kong
 12    0002.HK                  Australia
 13    0002.HK             Mainland China
 14    0002.HK                      India
 15    0002.HK    Southeast Asia & Taiwan
 16    0002.HK              Segment Total
 17    0002.HK                Unallocated
 18    0002.HK         Consolidated Total,
 None)

In [22]:
revenues

{'columnHeadersCount': 1,
 'data': [['2388.HK', ''],
  ['2318.HK', ''],
  ['0941.HK', ''],
  ['0175.HK', 105157280000],
  ['0175.HK', 618281000],
  ['0175.HK', 190818000],
  ['0175.HK', 488135000],
  ['0175.HK', 138220000],
  ['0175.HK', 2399000],
  ['0175.HK', 106595133000],
  ['0175.HK', 106595133000],
  ['0002.HK', 41623000000],
  ['0002.HK', 43013000000],
  ['0002.HK', 1495000000],
  ['0002.HK', 5269000000],
  ['0002.HK', 16000000],
  ['0002.HK', 91416000000],
  ['0002.HK', 9000000],
  ['0002.HK', 91425000000]],
 'headerOrientation': 'horizontal',
 'headers': [[{'displayName': 'Instrument'},
   {'displayName': 'Geographic Total Revenues (Calculated)',
    'field': 'TR.BGS.GEOTOTALREVENUE'}]],
 'rowHeadersCount': 1,
 'totalColumnsCount': 2,
 'totalRowsCount': 20}

In [ ]:
ek.get_symbology('STAN.L',from_symbol_type='RIC', to_symbol_type='ISIN', bestMatch=False)